name: Multi Event
on:
  push:
    branches:
      - main
      - dev
  pull_request:
    branches:
      - main
jobs:
  first_event:
    runs-on: ubuntu-latest
    steps:
      - name: Hello World
        run: echo "Hello World"

  second_event:
    runs-on: ubuntu-latest
    steps:
    - name: Multiple echo stmts
      run: |
        echo "REF: $GITHUB_REF"
        echo "Job ID: $GITHUB_JOB"
        echo "Action: $GITHUB_ACTION"
        echo "Actor: $GITHUB_ACTOR"
      
    
