name: cron schedule exemple
on:
  schedule:
    - cron: '0/30 * * * *'
    #- cron: '30 5 * * 2,4'

jobs:
  test_schedule:
    runs-on: ubuntu-latest
    steps:
#      - name: Not on Monday
#        if: github.event.schedule != '30 5 * * 1,3'
#        run: echo "This message will be skipped on Monday"
      - name: Every day
        run: echo "This step always run $(date)"